# Tensors

In [1]:
import torch

# 초기화되지 않은 5x3 행렬 생성
x = torch.empty(5, 3)
print(x)
print(x.size())

tensor([[9.5596e+02, 4.5580e-41, 9.5596e+02],
        [4.5580e-41, 2.2801e+00, 4.5580e-41],
        [2.2763e+00, 4.5580e-41, 2.2801e+00],
        [4.5580e-41, 2.2802e+00, 4.5580e-41],
        [2.2802e+00, 4.5580e-41, 2.2802e+00]])
torch.Size([5, 3])


In [2]:
# 무작위로 초기화된 5x3 행렬 생성
x = torch.rand(5, 3)
print(x)
print(x.dtype, x.size())

tensor([[0.4993, 0.2168, 0.7013],
        [0.4593, 0.6200, 0.0150],
        [0.1198, 0.4155, 0.6621],
        [0.3337, 0.8544, 0.4826],
        [0.0791, 0.2108, 0.2692]])
torch.float32 torch.Size([5, 3])


In [3]:
# 0으로 초기화된 5x3 행렬 생성, dtype으로 long을 설정
x = torch.zeros(5, 3, dtype=torch.long)
print(x)
print(x.dtype, x.size())

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])
torch.int64 torch.Size([5, 3])


In [4]:
# 직접 데이터를 넣어서 tensor 생성
x = torch.tensor([5.5, 3], dtype=torch.double)
print(x)
print(x.dtype, x.size())

tensor([5.5000, 3.0000], dtype=torch.float64)
torch.float64 torch.Size([2])


In [5]:
# tensor의 new_*()는 기존 tensor의 속성과 동일한 새로운 tensor를 생성

# x와 동일한 dtype을 가지는 5x3 크기의 ones 행렬 생성
x = x.new_ones(5, 3)
print(x)
print(x.dtype, x.size())

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
torch.float64 torch.Size([5, 3])


In [6]:
# torch.*_like()는 인자로 전달받은 tensor의 속성을 그대로 사용

# x와 동일한 크기를 가지는 5x3 크기의 random 행렬 생성
# (dtype을 지정해주지 않았다면, 동일하게 torch.float64로 속성을 받아옴)
x = torch.randn_like(x, dtype=torch.float)
print(x)
print(x.dtype, x.size())

tensor([[-0.3603,  1.8218, -2.4088],
        [-2.0575,  0.0539,  1.2491],
        [-0.2280, -1.5832,  1.5325],
        [ 0.6830, -0.0643, -1.0437],
        [-0.8801,  2.6887, -1.5798]])
torch.float32 torch.Size([5, 3])


# Operations

In [7]:
y = torch.rand(5, 3)
# 덧셈
print(x + y)

tensor([[-0.1186,  2.0782, -1.6997],
        [-1.7858,  0.7323,  1.6304],
        [ 0.0251, -0.8383,  2.0161],
        [ 1.5526,  0.0797, -0.0760],
        [-0.3410,  3.3292, -0.8600]])


In [8]:
# torch.add()로도 덧셈 가능
print(torch.add(x, y))

tensor([[-0.1186,  2.0782, -1.6997],
        [-1.7858,  0.7323,  1.6304],
        [ 0.0251, -0.8383,  2.0161],
        [ 1.5526,  0.0797, -0.0760],
        [-0.3410,  3.3292, -0.8600]])


In [9]:
# 덧셈 결과를 result에 담기
result = torch.empty(5, 3) # result = torch.empty_like(x)로도 가능
torch.add(x, y, out=result)
print(result)

tensor([[-0.1186,  2.0782, -1.6997],
        [-1.7858,  0.7323,  1.6304],
        [ 0.0251, -0.8383,  2.0161],
        [ 1.5526,  0.0797, -0.0760],
        [-0.3410,  3.3292, -0.8600]])


In [10]:
# in-place로 수행
y.add_(x)
print(y)

tensor([[-0.1186,  2.0782, -1.6997],
        [-1.7858,  0.7323,  1.6304],
        [ 0.0251, -0.8383,  2.0161],
        [ 1.5526,  0.0797, -0.0760],
        [-0.3410,  3.3292, -0.8600]])


In [11]:
# tensor는 numpy처럼 indexing이 가능
# 1열 출력
print(x[:, 1])

tensor([ 1.8218,  0.0539, -1.5832, -0.0643,  2.6887])


In [12]:
# view()는 tensor의 shape를 변경 (numpy의 reshape와 같은 역할을 하는 함수)
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


# Torch Tensor를 Numpy 배열로 변환

In [13]:
a = torch.ones(5)
print(a)
print(type(a))

tensor([1., 1., 1., 1., 1.])
<class 'torch.Tensor'>


In [14]:
# numpy()로 numpy로 변환 가능
b = a.numpy()
print(b)
print(type(b))

[1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>


In [15]:
# torch의 tensor랑 numpy array는 메모리를 공유
# 따라서, tensor의 값을 변경하면 참조하고 있던 numpy array도 변경됨
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


# Numpy 배열을 Torch Tensor로 변환

In [16]:
import numpy as np

a = np.ones(5)
print(a)
print(type(a))

[1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>


In [17]:
# from_numpy()로 numpy array를 torch tensor로 변환
b = torch.from_numpy(a)
print(b)
print(type(b))

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
<class 'torch.Tensor'>


In [18]:
# 마찬가지로 메모리를 공유
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


# CUDA Tensors

In [19]:
device = "cuda" if torch.cuda.is_available else "cpu"

In [20]:
y = torch.ones_like(x, device=device)
x = x.to(device)
z = x + y
print(z)

tensor([[ 1.3004,  1.5427,  0.8815,  0.6359],
        [ 0.3356,  1.7254,  0.7432,  1.0509],
        [ 0.2286, -0.8064, -0.0195,  0.6604],
        [ 1.8741,  1.7266,  0.5796,  1.8728]], device='cuda:0')


In [21]:
# to()를 사용해서 GPU 안팎으로 tensor를 옮길 수 있음
# to()는 dtype을 지정해줄 수도 있음
print(z.to("cpu", dtype=torch.double))

tensor([[ 1.3004,  1.5427,  0.8815,  0.6359],
        [ 0.3356,  1.7254,  0.7432,  1.0509],
        [ 0.2286, -0.8064, -0.0195,  0.6604],
        [ 1.8741,  1.7266,  0.5796,  1.8728]], dtype=torch.float64)
